vehicle:
  id: 4
  registration_number: "NS-012-GH"
  brand: "Ford"
  model: "Mustang"
  max_load_kg: 18500
  initial_latitude: 43.3209 # Niš
  initial_longitude: 21.8958

rabbitmq:
  url: "amqp://guest:guest@localhost:5672/"
  exchanges:
    - name: "simulator.vehicle.heartbeat"
      kind: "topic"
      durable: true
    - name: "simulator.vehicle.location"
      kind: "topic"
      durable: true
  connection_timeout: "10s"
  reconnect_delay: "5s"
  max_reconnect_attempts: 10

simulator:
  heartbeat_interval: "3s"
  reporting_interval: "10s"
  min_speed: 0
  max_speed: 90

logging:
  level: "info"
  format: "console"
  output_path: "stdout"
