services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-eurosupply
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - iot-network

  influxdb:
    image: influxdb:1.8
    container_name: influxdb-eurosupply
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
    volumes:
      - ./influxdb/data:/var/lib/influxdb
    networks:
      - iot-network

  redis:
    image: redis:7
    container_name: redis-eurosupply
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    networks:
      - iot-network
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  rabbitmq_data:

networks:
  iot-network:
    name: iot-network